### ISSUE TITLE
Looking for a way to cleanup the communal storage when the Vertica Cluster is deleted

### ISSUE THREAD

**Issue by alita1991** [vertica/vertica-kubernetes#1027]
Hi,

I'm seeking a method to clean up the communal storage for a Vertica Cluster when the VerticaDB CR is deleted.

```
communal:
    path: "s3://<bucket-name>/<key-name>"
    endpoint: http://path/to/endpoint
    credentialSecret: s3-creds  
```

This issue arises when attempting to delete and re-create the Vertica Cluster using the same bucket and key name.

Thanks

**Comment by qindotguan** [comment]
The communal storage was saved intentionally so you can revive the Vertica DB in the future. You can always manually remove it by using the AWS command:
`$ aws s3 rm s3://<bucket-name>/<key-name> --recursive`

To re-use the same bucket and key name, you can set the annotations "vertica.com/include-uid-in-path" to true in your CR, it will add a sub-folder under the <key-name>
```
apiVersion: vertica.com/v1
kind: VerticaDB
metadata:
  name: vertica-db
  annotations:
    vertica.com/include-uid-in-path: "true"
spec:
...
```

Please remember that you still need to call AWS command to remove the <uid> sub-folder under the <key-name> if you don't want to save it.
