### ISSUE TITLE
VerticaDB single-node reconfiguration does not recreate the pod

### ISSUE THREAD

**Issue by alita1991** [vertica/vertica-kubernetes#1082]
**Operator image:** opentext/verticadb-operator:25.1.0-0

**Config used to deploy verticadb**

```
apiVersion: vertica.com/v1
kind: VerticaDB
metadata:
  name: vertica-single
  namespace: integration
  annotations:
    vertica.com/k-safety: "0"
    vertica.com/vcluster-ops: "true"
spec:
  image: opentext/vertica-k8s:24.3.0-4-minimal
  communal:
    path: "s3://vertica/vertica-single-test"
    endpoint: http://minio.integration.svc:9000
    credentialSecret: minio-s3-creds
  local:
    requestSize: 10Gi
  subclusters:
    - name: defaultsubcluster
      size: 1
  shardCount: 1
```

**Config used to reconfigure verticadb**

```
apiVersion: vertica.com/v1
kind: VerticaDB
metadata:
  name: vertica-single
  namespace: integration
  annotations:
    vertica.com/k-safety: "0"
    vertica.com/vcluster-ops: "true"
spec:
  image: opentext/vertica-k8s:24.3.0-4-minimal
  communal:
    path: "s3://vertica/vertica-single-test"
    endpoint: http://minio.integration.svc:9000
    credentialSecret: minio-s3-creds
  local:
    requestSize: 10Gi
  subclusters:
    - name: defaultsubcluster
      size: 1
      resources:
        requests:
          cpu: 1
          memory: 1Gi
          ephemeral-storage: 64Mi
        limits:
          cpu: 4
          memory: 4Gi
          ephemeral-storage: 128Mi
  shardCount: 1
```

**Status**
The pod does not restart when a new configuration is applied; it only restarts when the image is updated

**Workaround**
Delete the pod manually
