### ISSUE TITLE
Backup / Restore for Vertica 24.x+

### ISSUE THREAD

**Issue by alita1991** [vertica/vertica-kubernetes#1087]
Hi,

I'm looking for a backup and restore procedure for VerticaDB 24.x+ that covers the following scenarios:
- The current VerticaDB cluster has failed, and I need to set up a new cluster and restore the backup
- I accidentally deleted a database and need to restore it

Later, I plan to use the procedure to automate backup and restore with Kanister. I'm aware that the vbr utility is no longer available starting with version 24.x.

Thank you

**Comment by ifalex** [comment]
I'm also interested in this procedure. As I see in official documentation vbr and admintools was removed from official image for vertica.
Despite of this, vbr is still regarded as the principal backup/restore procedure for non-containerized installations.
Therefore is there any plan to deprecate vbr? What are the plans for backup/restore for containerized installs?
Currently VerticaRestorePointsQuery does not cover all the scenarios that vbr would cover.

**Comment by qindotguan** [comment]
Containerized Vertica with 24.1+ now supports in-db backup and restore. If in-db restore points were created, we can restore the database to the saved in-db restore points:
https://docs.vertica.com/25.1.x/en/containerized/custom-resource-definitions/vertica-restorepoints-query/#restore-the-database

For example, suppose the original database failed or was deleted, we can edit the vdb CR (yaml file) to set initPolicy set to `Revive` and add a restorePoint section with a restore point (archive) specified. Make sure to use the original db communal storage in the CR:
```
  spec:
    initPolicy: Revive
    restorePoint:
      archive: "nightly"
      index: 1
    communal:
      path: s3://vertica-bucket/vertdb           # the original communal storage of the db
    ...
```
Once the CR is applied, you will get a db restored to the specified restore point.

In case there were no in-db restore points saved, we can always revive from the communal storage (without restore points specified) to get a running database:
```
  spec:
    initPolicy: Revive
    communal:
      path: s3://vertica-bucket/vertdb           # the original communal storage of the db
```
