### ISSUE TITLE
Remove namespace rule when scope is set to namespace

### ISSUE THREAD

**Issue by alita1991** [vertica/vertica-kubernetes#1313]
When the operator is configured with `scope: namespace`, the following RBAC rule becomes unnecessary:

```
# verticadb-operator-manager-role-cr.yaml
apiGroups:
  - ""
resources:
  - namespaces
verbs:
  - get
  - list
  - watch
```

This can be cleanly solved by making the RBAC rule conditional in the helm chart:

```
# verticadb-operator-manager-role-cr.yaml
{{- if eq .Values.controllers.scope "cluster" }}
- apiGroups:
  - ""
  resources:
    - namespaces
  verbs:
    - get
    - list
    - watch
{{- end }}
```

The change has been tested and confirmed to work correctly in namespace mode.
