### ISSUE TITLE
Improve RBAC for leader election role

### ISSUE THREAD

**Issue by alita1991** [vertica/vertica-kubernetes#1314]
The RBAC rules for configmaps and leases are incorrect due to improper API group/resource associations:

- The "" (core) API group does not include the leases resource
- The coordination.k8s.io API group does not include the configmaps resource

```
# verticadb-operator-leader-election-role-role.yaml
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - configmaps
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
```

The corrected version of the rules should look like this:

```
# verticadb-operator-leader-election-role-role.yaml
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
```
