### ISSUE TITLE
Nodes unreachable

### ISSUE THREAD

**Issue by ioachim-hub** [vertica/vertica-kubernetes#147]
Hello,

I tried to deploy vertica on kind with vertica-operator, but the nodes are unreachable at CRD installation.
I use 3 replicas of vertica, with standard(non-enterprise) container.
I use minio for storage provisioner.

# This is a reproducer:

## Create kind cluster

Create a file named kind.yaml with the content:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
nodes:
  - role: control-plane
  - role: worker
    image: docker.io/kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
  - role: worker
    image: docker.io/kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
  - role: worker
    image: docker.io/kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
networking:
  ipFamily: ipv6
  apiServerAddress: "::"
  apiServerPort: 6443
```

Run the commands:

To create kind cluster (you need to be in kind.yaml directory):
```
kind create cluster --config kind.yaml
```

To install vertica CRD:
```
kubectl apply -f https://github.com/vertica/vertica-kubernetes/releases/download/v1.2.0/verticadbs.vertica.com-crd.yaml
```

To install cert-manager CRD:
```
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.7.0/cert-manager.crds.yaml
```

## Create vertica CRDs chart

Create a helm chart named `vertica` with this files in `templates/` directory:
`secret.yaml`:
```
apiVersion: v1
kind: Secret
metadata:
  name: vertica-secret
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
type: "kubernetes.io/storageos"
data:
  accesskey:
    {{ "vertica" | b64enc }}
  secretkey:
    {{ "yU8WBCC9B7" | b64enc }}
```

`vertica-crd_default.yaml`:
```
apiVersion: vertica.com/v1beta1
kind: VerticaDB
metadata:
  name: vertica-sample
spec:
  communal:
    path: "s3://vertica-bucket"
    endpoint: http://minio:9000
    credentialSecret: vertica-secret
  subclusters:
    - name: defaultsubcluster
      size: 3
```

## Deploy charts

Create a file named helmfile.yaml with this content:
```
# yaml-language-server: $schema=https://json.schemastore.org/helmfile.json
helmDefaults:
  timeout: 600
  skipDeps: true
  historyMax: 2

repositories:
  - name: vertica-charts
    url: https://vertica.github.io/charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: cert-manager
    url: https://charts.jetstack.io

missingFileHandler: Error

releases:
  - name: cert-manager
    chart: cert-manager/cert-manager
    version: v1.7.0
    values:
      - image:
          registry: "quay.io"
          repository: "jetstack/cert-manager-controller"
          pullPolicy: Always

  - name: vertica-operator
    chart: vertica-charts/verticadb-operator
    needs:
      - "cert-manager"

  - name: minio
    chart: bitnami/minio
    values:
      - image:
          registry: docker.io
          repository: bitnami/minio
          tag: 2022.1.8-debian-10-r1
          debug: true # for this moment
      - clientImage:
          registry: docker.io
          repository: bitnami/minio-client
          tag: 2022.1.7-debian-10-r1
      - mode: "distributed"
      - podAntiAffinityPreset: soft
      - statefulset:
          updateStrategy:
            type: RollingUpdate
          podManagementPolicy: Parallel
          replicaCount: 4 # at least 4 nodes are required
          zones: 1
          drivesPerNode: 1
      - volumePermissions:
          enabled: true
          image:
            registry: "docker.io"
            repository: "bitnami/bitnami-shell"
            tag: "10-debian-10-r305"
            pullPolicy: "IfNotPresent"
      - auth:
          rootUser: admin
          rootPassword: 69WCTt7MyT
      - metrics:
          serviceMonitor:
            # TODO: enable when actually start monitoring services
            enables: false
      - provisioning:
          enabled: true
          buckets:
            - name: vertica-bucket
              region: eu
              withLock: true
              quota:
                type: hard
                size: 10GB
              lifecycle:
                - id: TestPrefix7dRetention
                  prefix: test-prefix
                  disabled: false
                  expiry:
                    days: 7
          users:
            - username: vertica
              password: yU8WBCC9B7
              disabled: false
              policies:
                - readwrite
      - persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce

  - name: vertica
    chart: vertica-chart
```

To deploy the charts execute command from helmfile.yaml directory:
```
helmfile sync
```
