### ISSUE TITLE
Operator controller allows old TLS versions

### ISSUE THREAD

**Issue by nyikesda** [vertica/vertica-kubernetes#155]
Our vulnerability scanners raised an issue because, the operator controller allows TLS v1.0/1.1 on port 9443.
Please allow only TLS 1.2, because of the legacy versions have many vulnerabilities.

**Comment by spilchen** [comment]
To clarify, did you mean port 8443?  If so, this is the https://github.com/brancz/kube-rbac-proxy.  We currently run with 0.8.0.  In the latest version, 0.11.0, they have an option to specify the TLS version (`--tls-min-version`).  So, on the surface, it seems reasonable that we can upgrade and/or use this option.

**Comment by nyikesda** [comment]
I mean this port from the kubernetes deployment resource:
```yaml      name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
```
Is it chnaged after 1.2.0?
