### ISSUE TITLE
 Provide a way to automate backups

### ISSUE THREAD

**Issue by vyaslav** [vertica/vertica-kubernetes#209]
Currently to automate backups we've implemented UDx in python to run vbr and trigger it via a simple cronjob:
```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: vertica-backup
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: vertica-backup
            ...
```
But this doesn't work for multi-node setups and it would be great to have an official way of doing the same.
