### ISSUE TITLE
readOnlyRootFilesystem = True does not work in operator deployment

### ISSUE THREAD

**Issue by nyikesda** [vertica/vertica-kubernetes#253]
We have to set readOnlyRootFilesystem = True in the operator "manager" container's securityContext, but this modification will cause error in the operator:

2022-08-29T14:10:17.461Z        ERROR   controller.verticadb    Reconciler error        {"reconciler group": "[vertica.com](http://vertica.com/)", "reconciler kind": "VerticaDB", "name": "eric-eea-analytical-processing-database-cr", "namespace": "vertica-pcr-1127", "error": "open /tmp/accept_eula.py.2764540482: read-only file system"}
[sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:317
[sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266
[sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227

**Comment by nyikesda** [comment]
I have solved it in operator deployment.yaml with:
```yaml
# { ... }
volumeMounts:
        - name: tmp
          mountPath: "/tmp"
# { ... }
volumes:
      - name: tmp
        emptyDir:
          sizeLimit: "10Mi"
          medium: "Memory"
```
