### ISSUE TITLE
Database could not be revived

### ISSUE THREAD

**Issue by unix-way** [vertica/vertica-kubernetes#335]
Hello,

I'm trying to revive the database using a (slightly modified) manifest generated by vdb-gen:

```
apiVersion: vertica.com/v1beta1
kind: VerticaDB
metadata:
  name: xxx
spec:
  autoRestartVertica: true
  communal:
    credentialSecret: gcs-creds
    endpoint: ""
    path: gs://xxx/
    region: US-WEST1
  dbName: xxx
  image: vertica/vertica-k8s:11.0.2-0
  initPolicy: Revive
  kSafety: "1"
  licenseSecret: vertica-license
  local:
    catalogPath: /var/lib/verticadb/catalog
    dataPath: /var/lib
    depotPath: /var/lib/verticadb/depot
    requestSize: 65536Mi
    storageClass: ssd
  reviveOrder:
  - podCount: 6
    subclusterIndex: 0
  shardCount: 6
  subclusters:
  - affinity: {}
    isPrimary: true
    name: default
    resources:
      requests:
        cpu: 2
        memory: 8Gi
      limits:
        cpu: 4
        memory: 16Gi
    size: 6
    serviceType: LoadBalancer
    serviceAnnotations: {}
  superuserPasswordSecret: xxx-su-passwd
  temporarySubclusterRouting:
    template:
      affinity: {}
      isPrimary: false
      name: ""
      resources: {}
      size: 0
  upgradePolicy: ""
```

I see 6 pods created after I apply it, but the database revive command fails with the following error (the below logs come from `v_xxx_node0001`):

```
Attempting to retrieve file: [gs://xxx/metadata/xxx/cluster_config.json]

Validated 6-node database xxx defined at communal storage gs://xxx/.
Cluster lease has expired.
Preparation succeeded all hosts

Calculated necessary addresses for all nodes.
Starting to bootstrap nodes. Please wait, databases with a large catalog may take a while to initialize.
>>Calling bootstrap on node v_xxx_node0002 (240.4.41.11)
>>Calling bootstrap on node v_xxx_node0003 (240.4.41.12)
>>Calling bootstrap on node v_xxx_node0004 (240.4.59.13)
>>Calling bootstrap on node v_xxx_node0005 (240.4.0.64)
>>Calling bootstrap on node v_xxx_node0006 (240.4.12.46)

Database could not be revived.
Error: Not enough primary nodes to revive the database.
Successful primary nodes: None
```

Right before this, I see a correct `revive_db` command with 6 addresses listed after the `--hosts` option:

```
sudo --preserve-env su dbadmin -- /opt/vertica/bin/admintools -t revive_db \
    --hosts=240.4.59.12,240.4.41.11,240.4.41.12,240.4.59.13,240.4.0.64,240.4.12.46 \
    --communal-storage-location=gs://xxx/ \
    --communal-storage-params=/home/dbadmin/auth_parms.conf \
    --database xxx
```

Is this reproducible: yes
Operator version: 1.9.0
Database version: 11.0.2-18

**Comment by spilchen** [comment]
Usually what the 'Not enough primary nodes' error means is that we hit problems trying to revive at a majority of primary nodes (all in your case). It's not an error saying there aren't enough primary nodes. We have validated that there are 6 primaries and the CR has 6 primaries.

There might be an indication of what is going on by looking at /opt/vertica/log/adminTools.log. Can you provide your adminTools.log? Maybe start with the pod that is driving the revive.

**Comment by unix-way** [comment]
Thank you, the problem was that image version `vertica-k8s:11.0.2-0` was older than the database version `11.0.2-18`. Since there is no image for `11.0.2-18`, I built my own using the `Dockerfile` in `docker-vertica`, but now I'm facing a different issue: the operator is trying to run a command

```
sh -c cat > /opt/vertica/config/accept_eula.py && /opt/vertica/oss/python3/bin/python3 /opt/vertica/config/accept_eula.py
```

but it fails with

```
sh: 1: cannot create /opt/vertica/config/accept_eula.py: Permission denied
```

` /opt/vertica/config` is mounted as a volume owned by `root`. In the `11.0.2-0` image, there were commands in the entrypoint script chowning the mounted directories to `dbadmin`, but the new image doesn't have them. Is there a way to fix that?

**Comment by unix-way** [comment]
I managed to move a bit further by building the image from commit e7208d8 (tag v1.9.0), now it's failing with

```
Attempting to retrieve file: [gs://xxx/metadata/xxx/cluster_config.json]

Validated 6-node database xxx defined at communal storage gs://xxx/.
Cluster lease has expired.

Database could not be revived.
Error: Database xxx already exists.
If you want to force a new revive from communal storage on this cluster, please clean up the existing database first. You can drop the existing database by running: [admintools -t drop_db -d xxx]
```

**Comment by spilchen** [comment]
> /opt/vertica/config is mounted as a volume owned by root. In the 11.0.2-0 image, there were commands in the entrypoint script chowning the mounted directories to dbadmin, but the new image doesn't have them.

Yes, this was changed to use the `fsGroup` property in the pod's security context. It sounds like you got past this part, but could you confirm that your vertica pods have this set?

```
spec:
  ...
  securityContext:
    fsGroup: 5000
```
If it doesn't have that, you may need to upgrade the operator to the latest version (1.9.0).

> re: Error: Database xxx already exists.

This happens when the database is already in /opt/vertica/config/admintools.conf. If you haven't already, can you try deleting the VerticaDB and the PVCs. Then recreating the VerticaDB again?

**Comment by unix-way** [comment]
Thank you for your response!

**I already have the latest version of the operator**

```
➜  ~ helm ls -n verticadb
NAME     	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART                   	APP VERSION
verticadb	verticadb	1       	2023-02-10 14:11:27.333138 -0800 PST	deployed	verticadb-operator-1.9.0
```

I checked - pods don't have `fsGroup` set in their security context. The pod security context is empty, and the container security context is

```
    securityContext:
      capabilities:
        add:
        - SYS_CHROOT
        - AUDIT_WRITE
        - SYS_PTRACE
```

I tried adding `fsGroup` to the CR spec, but got the following error when attempted to apply it:

```
error: error validating "xxx-cr.yaml": error validating data: ValidationError(VerticaDB.spec.securityContext): unknown field "fsGroup" in com.vertica.v1beta1.VerticaDB.spec.securityContext; if you choose to ignore these errors, turn validation off with --validate=false
```

The database is indeed already in `/opt/vertica/config/admintools.conf`. Yes, I deleted the vdb resource and all the PVCs before redeploying, and also made sure the PVs were all gone before I reapplied the manifest, so the PDs are pristine, but I am still getting the same error.
