### ISSUE TITLE
Cannot run vertica in istio environment

### ISSUE THREAD

**Issue by danieleharel** [vertica/vertica-kubernetes#361]
Trying to deploy the vertica operator with 3 pods connected to bucket in GCP.
shardCount configured to 6
image: vertica/vertica-k8s:12.0.3-0
Helm chart 1.8.0
bucket is created.
1/3 pods are up 
operator logs get stuck on
ExecInPod entry	{"verticadb": "verticadb/verticadb", "pod": "verticadb/verticadb-primary-subcluster-0", "command": "sudo --preserve-env su dbadmin -- /opt/vertica/bin/admintools -t create_db .......

Anyone faced this issue?

**Comment by spilchen** [comment]
What is output of the create_db command? It should be the next entry in the operator log. Are you running istio / ASM?

**Comment by danieleharel** [comment]
> 

Thanks for the response.
There is not output after the create_db, just gets stuck.
And istio

**Comment by spilchen** [comment]
At this point you cannot deploy Vertica in k8s environment running with istio. istio requires that we bind and listen on localhost / 127.0.0.1. But our internal node-to-node communication (spread) binds to the pod IP. We are investigating this issue. But, I don't have an ETA on when this will be fixed.

**Comment by spilchen** [comment]
There are a few istio options that you can do to get Vertica running.

1. Set the interception mode to be TPROXY. This can be done by setting an annotation in the CR field `spec.annotations`:
```
apiVersion: vertica.com/v1beta1
kind: VerticaDB
metadata:
  name: v
spec:
  annotations:
    sidecar.istio.io/interceptionMode: TPROXY
 ...
```

This worked for me running istio. But not in GCP, where istio is offered as a managed service called [Anthos Service Mesh (ASM)](https://cloud.google.com/anthos/service-mesh)

2. Disable NAT on a port that we use for internal vertica-to-vertica communication. Again, this can be set by adding an annotation to `spec.annotations`:

```
apiVersion: vertica.com/v1beta1
kind: VerticaDB
metadata:
  name: v
spec:
  annotations:
    traffic.sidecar.istio.io/excludeInboundPorts: "5434"
...
```

This worked on GCP ASM.
