### ISSUE TITLE
CA path for the https communal storage

### ISSUE THREAD

**Issue by nyikesda** [vertica/vertica-kubernetes#45]
If I’m right then to connect to an s3 communal storage through tls I have to configure CA cert file path.
Currently there is no option to do that. I can configure https endpoint in the spec.communal.endpoint, but there is no option to set CA file path.
Vertica supports to do that with the awscafile option, and it would be important to us, to be able to configure this in the spec.communal.

**Matt answer:**
It was already on our radar, so we were planning on addressing it by end of September.  The CR was going to have a way to mount generic certs and specify a CA for communal access.
```yaml
apiVersion: vertica.com/v1beta1
kind: VerticaDB
metadata:
  name: sample
spec:
  communal:
    path: "s3://nimbusdb/db"
    endpoint: "https://minio"
    credentialSecret: s3-auth
    caFile: /certs/aws-certs/root_cert.pem
  certSecrets:
    - name: aws-cert  
  subclusters:
    - name: sc1
```
The path for spec.communal.ca, is container relative and uses the cert that was mounted through spec.certSecrets.
