### ISSUE TITLE
security issues with the hard coded container securityContext

### ISSUE THREAD

**Issue by nyikesda** [vertica/vertica-kubernetes#970]
Actually the following container security context is generated by the operator to the server container in the generated statefulset:
```yaml
securityContext:
          capabilities:
            add:
            - SYS_CHROOT
            - AUDIT_WRITE
            - SYS_PTRACE
```

SYS_PTRACE  capability can be dangerous and it is a security hole in a production environment. I cannot see any option from the operator code to disable this capability.

Why is it forced? Could you please give an option to disable it or any work arounds to not has it in the generated statefulset?
